version: "3"
services:
  jenkins:
    build: 
      args:
        HOST_DOCKER_GID: 1001
    container_name: jenkins
    image: meir215/jenkins
    hostname: jenkins
    ports:
      - 8880:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      # - ./config.yml:/var/jenkins_config.yml
volumes:
  jenkins_home:
    external: true